# Generated by Django 2.2.15 on 2021-02-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_auto_20210214_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicchatroom',
            options={'verbose_name': '公共聊天室', 'verbose_name_plural': '公共聊天室'},
        ),
        migrations.AlterModelOptions(
            name='publicchatroommessage',
            options={'verbose_name': '公共聊天室消息', 'verbose_name_plural': '公共聊天室消息'},
        ),
        migrations.AlterModelTable(
            name='publicchatroom',
            table='tb_public_chatroom',
        ),
        migrations.AlterModelTable(
            name='publicchatroommessage',
            table='tb_public_chatroom_message',
        ),
    ]
