# Generated by Django 2.2.15 on 2021-02-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommessage',
            options={'verbose_name': '私聊消息', 'verbose_name_plural': '私聊消息'},
        ),
        migrations.AlterModelOptions(
            name='privatechatroom',
            options={'verbose_name': '私聊', 'verbose_name_plural': '私聊'},
        ),
        migrations.AlterModelTable(
            name='chatroommessage',
            table='tb_private_chatroom_message',
        ),
        migrations.AlterModelTable(
            name='privatechatroom',
            table='tb_private_chatroom',
        ),
    ]
